# Generated by Django 5.2 on 2025-05-05 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('כותרת_ראשית', models.CharField(max_length=255)),
                ('כותרת_משנית', models.CharField(max_length=255)),
                ('תאריך', models.DateField()),
                ('מיקום_ידני', models.CharField(blank=True, max_length=500)),
                ('מיקום', models.CharField(max_length=255)),
                ('שעת_התחלה', models.TimeField()),
                ('תמונה', models.ImageField(upload_to='tours_images/')),
                ('טלפון_מדריך', models.CharField(blank=True, max_length=20, null=True)),
                ('עלות', models.DecimalField(decimal_places=2, help_text='יש להזין את העלות בשקלים חדשים (₪)', max_digits=8, null=True, verbose_name='עלות הסיור')),
            ],
        ),
        migrations.CreateModel(
            name='TourGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_guide_first_name', models.CharField(max_length=100, verbose_name='שם פרטי')),
                ('tour_guide_last_name', models.CharField(max_length=100, verbose_name='שם משפחה')),
                ('tour_guide_phone', models.CharField(max_length=20, verbose_name='טלפון נייד')),
                ('tour_guide_email', models.EmailField(max_length=254, verbose_name='כתובת מייל')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='כתובת מגורים')),
                ('license_file', models.FileField(blank=True, null=True, upload_to='licenses/', verbose_name='קובץ רישיון הדרכה')),
                ('license_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='מספר רישיון')),
                ('languages', models.CharField(blank=True, max_length=255, null=True, verbose_name='שפות הדרכה')),
                ('specialties', models.CharField(blank=True, max_length=255, null=True, verbose_name='תחומי התמחות')),
                ('experience', models.TextField(blank=True, null=True, verbose_name='ניסיון מקצועי')),
                ('recommendations', models.TextField(blank=True, null=True, verbose_name='המלצות או קישורים')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('שם_פרטי', models.CharField(max_length=255)),
                ('שם_משפחה', models.CharField(max_length=255)),
                ('תעודת_זהות', models.CharField(max_length=20, unique=True)),
                ('טלפון', models.CharField(max_length=20)),
                ('אימייל', models.EmailField(max_length=254)),
                ('נוכחות', models.BooleanField(default=False)),
                ('סיור', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='tours.tour')),
            ],
        ),
        migrations.AddField(
            model_name='tour',
            name='שם_מדריך',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='tours.tourguide'),
        ),
    ]
