# Generated by Django 5.1.4 on 2025-04-27 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('כותרת_ראשית', models.CharField(max_length=255)),
                ('כותרת_משנית', models.CharField(max_length=255)),
                ('תאריך', models.DateField()),
                ('מיקום', models.CharField(max_length=255)),
                ('שעת_התחלה', models.TimeField()),
                ('שם_מדריך', models.CharField(max_length=255)),
                ('תמונה', models.ImageField(upload_to='tours_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('שם_פרטי', models.CharField(max_length=255)),
                ('שם_משפחה', models.CharField(max_length=255)),
                ('תעודת_זהות', models.CharField(max_length=20)),
                ('טלפון', models.CharField(max_length=20)),
                ('אימייל', models.EmailField(max_length=254)),
                ('סיור', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='tours.tour')),
            ],
        ),
    ]
