# Generated by Django 5.1.4 on 2025-04-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='תעודת_זהות',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
