# Generated by Django 5.1.4 on 2025-04-28 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_alter_registration_תעודת_זהות'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='נוכחות',
            field=models.BooleanField(default=False),
        ),
    ]
