# Generated by Django 5.1.4 on 2025-04-28 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_registration_נוכחות'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='מיקום_ידני',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
