# Generated by Django 5.2 on 2025-04-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_tour_מיקום_ידני'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='טלפון_מדריך',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
